#!/usr/bin/python
import csv
import sys

lines = []
with open("swipe") as file:
    line = file.readline()
    while line != "":
        split = line.split()
        if len(split) >= 4 and split[4] == 'ABS_MT_POSITION_X':
            y = file.readline()
            if y != '' and y.split()[4] == 'ABS_MT_POSITION_Y':
                lines.append([str(int(split[5], 16)), str(int(y.split()[5], 16)), split[1][:-1]])

        line = file.readline()


with open('swipe.csv', 'w') as file:
    for line in lines:
        file.write(str(line)[1:-1].replace("'", '') + ', ' + sys.argv[1] + '\n')


